PS-8830 Document new open_tables_with_triggers status variable (8.0)
percona/psmysql-docs pull request #157
Opened 2023-06-29 09:51 UTC by patrickbirch

modified:   docs/ps-variables.md

2023-06-29 11:43 UTC, alina-derkach-oaza approved these changes
LGTM

2023-09-08 11:47 UTC, dlenev requested changes
Hello Patrick!

I have only one minor suggestion about this patch. Otherwise it looks good to me.

2023-09-08 11:47 UTC, dlenev commented on docs/flexibility/trigger-updates.md
> +| `Open_tables_with_triggers` | The current number of TABLE instances with fully-loaded triggers in the Table cache. |
Perhaps it is better to be consistent with description of other status variables in this table and say "... in the `table_open_cache`." instead ?

2023-09-08 12:32 UTC, dlenev approved these changes
LGTM.

2023-09-08 12:38 UTC, alina-derkach-oaza approved these changes

2023-09-26 10:35 UTC, merged