PS-8898 Document group replication variables (8.0)
percona/psmysql-docs pull request #176
Opened 2023-08-28 08:58 UTC by patrickbirch

modified:   docs/replication/group-replication-system-variables.md

2023-08-29 05:37 UTC, venkatesh-prasad-v approved these changes

2023-08-29 05:43 UTC, venkatesh-prasad-v requested changes

2023-08-29 05:43 UTC, venkatesh-prasad-v commented on docs/replication/group-replication-system-variables.md
> +| Measured in | seconds |
A small correction: This variable is the actually the number of times SSL_accept() is called before closing the connection. So I don't think "Measured in seconds" is appropriate here.
```suggestion
| Measured in | seconds |
```

2023-09-05 08:45 UTC, venkatesh-prasad-v approved these changes

2023-09-26 10:02 UTC, alina-derkach-oaza approved these changes
LGTM

2023-09-26 10:34 UTC, merged