PS-8926 8.1.0-1 release notes and release tasks (8.1 innovation)
percona/psmysql-docs pull request #208
Opened 2023-11-15 17:08 UTC by patrickbirch

deleted:    docs/release-notes-index.md
	new file:   docs/release-notes/8.1.0-1.md
	new file:   docs/release-notes/release-notes-index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2023-11-16 13:48 UTC, percona-ysorokin requested changes

2023-11-16 13:48 UTC, percona-ysorokin commented on docs/release-notes/8.1.0-1.md
> +* `audit_log`
```suggestion
* `component_keyring_vault`
* `component_masking_functions`
* `component_binlog_utils`
* `component_percona_udf`
* `component_audit_log_filter`
```

2023-11-16 13:48 UTC, percona-ysorokin commented on docs/release-notes/8.1.0-1.md
> +* `audit_log`
I would also regroup this a bit.
```
component_masking_functions
component_binlog_utils
component_percona_udf
```
are fine here (simplification with INSTALL COMPONENT is the key point)

2023-11-16 13:48 UTC, percona-ysorokin commented on docs/release-notes/8.1.0-1.md
> +* `audit_log`
At the same time `component_keyring_vault ` and `component_audit_log_filter` deserve individual paragraphs (please see the Engineering meeting presentation for more details).

2023-11-16 13:48 UTC, percona-ysorokin commented on docs/release-notes/8.1.0-1.md
> +* `audit_log`
Also, a paragraph about Percona MTR test cases reorganizations would also be nice (the same presentation).

2023-11-16 13:48 UTC, percona-ysorokin commented on docs/release-notes/8.1.0-1.md
> +* The `keyring_value` plugin is removed.
```suggestion
* The `keyring_vault` plugin is removed.
```

2023-11-22 18:38 UTC, percona-ysorokin approved these changes
LGTM with one comment addressed

2023-11-22 18:38 UTC, percona-ysorokin commented on docs/release-notes/8.1.0-1.md
> +* The `audit_log` v1 plugin is removed.
Already in the list

2023-11-24 14:28 UTC, alina-derkach-oaza approved these changes

2023-11-24 14:34 UTC, eleo007 approved these changes

2023-11-27 18:59 UTC, merged