PS-9074 8.0.36-28 release notes and release note tasks (8.0)
percona/psmysql-docs pull request #263
Opened 2024-01-19 10:18 UTC by patrickbirch

new file:   docs/release-notes/8.0.36-28.md
	modified:   docs/release-notes/release-notes_index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-02-15 13:47 UTC, percona-ysorokin requested changes

2024-02-15 13:47 UTC, percona-ysorokin commented on docs/release-notes/8.0.36-28.md
> +* OpenSSL is now version 3.0.12.
The issue is that we almost always use the OpenSSL libraries from the OS.
Even Oracle says it more carefully
```
For platforms on which OpenSSL libraries are bundled, the linked OpenSSL library for MySQL Server has been updated to version 3.0.12
```
So, I would simply remove this item from the highlights.

2024-02-15 13:47 UTC, percona-ysorokin commented on docs/release-notes/8.0.36-28.md
> +* Updated GnuPG build key (A8D3785C). This key is used to sign MySQL downloadable packages. The previous key has expired. For details, see [Signature checking using GNUPG].
This is irrelevant to Percona products. Percona packages use completely different set of keys for package signing.
Please, remove.

2024-02-15 13:47 UTC, percona-ysorokin commented on docs/release-notes/8.0.36-28.md
> +* Updated GnuPG build key (A8D3785C). This key is used to sign MySQL downloadable packages. The previous key has expired. For details, see [Signature checking using GNUPG].
Instead, I would put
```
The hashing algorithm employed yielded poor performance when using a HASH field to check for uniqueness. (Bug #109548, Bug #34959356)
```
as a noticeable improvement.

2024-02-26 12:22 UTC, percona-ysorokin approved these changes
LGTM

2024-02-26 16:10 UTC, alina-derkach-oaza commented on docs/release-notes/8.0.36-28.md
> +[PS-9018]: The replica stalls when `log_slave_updates=0`and a DDL is executed against a non-replicated database on that replica.
`log_slave_updates=0`and -> add a space

`log_slave_updates=0`and a DDL is -> are

2024-03-04 09:10 UTC, alina-derkach-oaza approved these changes

2024-03-04 13:45 UTC, merged