PS-9098 Release notes for 5.7 EOL update 5.7.44-49
percona/psmysql-docs pull request #276
Opened 2024-02-13 01:19 UTC by patrickbirch

On branch ps-9098
	new file:   docs/release-notes/5.7.44-49.md
	modified:   docs/release-notes/release-notes_index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-02-13 11:15 UTC, VarunNagaraju commented on docs/release-notes/5.7.44-49.md
> +[CVE-2023-5363]: openssl.org/CVE-2023-5363
The url for CVE-2023-5363 should be https://www.openssl.org/news/vulnerabilities.html#CVE-2023-5363.

2024-02-13 11:38 UTC, VarunNagaraju approved these changes
LGTM

2024-02-13 11:54 UTC, alina-derkach-oaza approved these changes
Good

2024-02-20 09:36 UTC, sleto-it requested changes

2024-02-20 09:36 UTC, sleto-it commented on docs/release-notes/5.7.44-49.md
> +!!! important
These two sentences are a bit confusing. I recommend we change them to explain better that this is a release within the 5.7 EOL program. I might come back at some point and recommend some text - but wanted to flag this in the meantime. Thank you

2024-02-20 10:03 UTC, VarunNagaraju commented on docs/release-notes/5.7.44-49.md
> +        $ sudo yum update; sudo yum install openssl-3.0.12;
The versions suffix(-3.0.12) is not required here. A simple **_yum install openssl_** will do. It will install the latest version of openssl library available for the platform. It will also install the required dependencies(openssl-libs-3.0.x-* and openssl-devel-3.0.x-*).

2024-02-20 10:12 UTC, VarunNagaraju commented on docs/release-notes/5.7.44-49.md
> +  * [Debian 12]
[Oracle linux 9] can be added here with the url, https://linux.oracle.com/errata/ELSA-2024-0310.html.

2024-02-21 04:49 UTC, VarunNagaraju commented on docs/release-notes/5.7.44-49.md
> +* [Oracle Linux 9]
These 3 URLs can be removed since the info about openssl patched versions is available in detail below.

Keep the sentence : "The operating systems may port these fixes into the default versions of the libraries installed in the systems. "

2024-02-21 13:13 UTC, VarunNagaraju commented on docs/release-notes/5.7.44-49.md
> +[upgrading the third-party libraries]: #instructions-to-upgrade-third-party-libraries
Broken link. Perhaps, it should be **_#upgrade-third-party-libraries_**?

2024-02-21 13:14 UTC, sleto-it requested changes

2024-02-21 13:14 UTC, sleto-it commented on docs/release-notes/5.7.44-49.md
> +This release is part of the 5.7 EOL program. The fixes are available to [Post MySQL 5.7 EOL support customers]. Community members can [build this release from source].
thanks for improving this one, and sorry have not had enough time to get back earlier or suggest exact changes to make.
but wanted to flag something else, in the meantime.  i recommend we link to our own page on how to compile. If for any reason we need to link to an external page, we should still at least share which repository and branch to use: the 5.7 branch on percona server github.   We have not in this case, so this is not that understandable to user how to compile.   please note, we have two pages, https://percona-server-docs-5-7-pr-276.onrender.com/installation/git-source-tree.html and also https://percona-server-docs-5-7-pr-276.onrender.com/installation/compile.html we can probably link the first.

2024-02-21 13:14 UTC, sleto-it commented on docs/release-notes/5.7.44-49.md
> +We recommend that you either [upgrade to MySQL 8.0 or stay on 5.7; we'll support you].
still do not like it much. I will get back.

2024-02-21 13:26 UTC, VarunNagaraju commented
I remember Steve mentioning about adding a prefix [EOL] to the heading.
Other than that, looks good from my side.

2024-03-13 13:04 UTC, alina-derkach-oaza commented on docs/installation/binary-tarball.md
> +| Full    | Percona-Server-<release>/private/[CLIENTID]-[TOKEN]/Percona-Server-5.7/Percona-Server-{{release}}/binary/tarball/Percona-Server-{{release}}-Linux.x86_64.glibc2.17.tar.gz   | Contains bina
The <release> variables does not work

This one `Percona-Server-<release>/private/ `looks like `Percona-Server-/private/` in preview

2024-03-13 14:00 UTC, alina-derkach-oaza approved these changes

2024-03-14 17:07 UTC, merged