PS-9079 Release notes for Percona Server for MySQL 8.3.0-1
percona/psmysql-docs pull request #292
Opened 2024-03-19 14:21 UTC by alina-derkach-oaza

modified:   .github/workflows/main.yml
	new file:   docs/release-notes/8.3.0-1.md
	modified:   docs/release-notes/release-notes-index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-03-19 14:42 UTC, patrickbirch commented on docs/release-notes/8.3.0-1.md
> +* MyISAM tables are no longer supported.
I think it's still supported.

2024-03-19 16:41 UTC, alina-derkach-oaza commented on docs/release-notes/8.3.0-1.md
> +* MyISAM tables are no longer supported.
rewritten

2024-04-01 08:48 UTC, patrickbirch approved these changes
Good

2024-04-15 12:06 UTC, percona-ysorokin requested changes

2024-04-15 12:06 UTC, percona-ysorokin commented on docs/release-notes/8.3.0-1.md
> +
Please add
https://perconadev.atlassian.net/browse/PS-9125
as well

2024-04-15 12:06 UTC, percona-ysorokin commented on docs/release-notes/8.3.0-1.md
> +* Implements tagged GTIDs (Global Transaction Identifiers) to group related transactions. This helps enhance replication management and simplify tracking transaction dependencies.
Also our Binary Log UDFs were adapted to work properly with Tagged GTIDs
https://github.com/percona/percona-server/commit/92cb30d2fcca18ad86f387259af4a2b4e520ea3d
`Make sure Binlog Utils UDFs are compatible with new GTID format (tagged GTIDs)` item from the merge TODO list

2024-04-15 12:06 UTC, percona-ysorokin commented on docs/release-notes/8.3.0-1.md
> +
And
https://perconadev.atlassian.net/browse/PS-9083

2024-04-15 12:55 UTC, alina-derkach-oaza commented on docs/release-notes/8.3.0-1.md
> +* Implements tagged GTIDs (Global Transaction Identifiers) to group related transactions. This helps enhance replication management and simplify tracking transaction dependencies.
Added

2024-04-15 12:55 UTC, alina-derkach-oaza commented on docs/release-notes/8.3.0-1.md
> +
Added

2024-04-15 15:29 UTC, percona-ysorokin approved these changes
LGTM

2024-04-16 13:59 UTC, merged