PS-9250 Release notes for 5.7.44-50 (post-EOL 2)
percona/psmysql-docs pull request #335
Opened 2024-06-06 10:06 UTC by patrickbirch

On branch ps-9250
	new file:   docs/release-notes/5.7.44-50.md
	modified:   docs/release-notes/release-notes_index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-06-06 12:02 UTC, alina-derkach-oaza approved these changes
LGTM

2024-06-11 12:09 UTC, alina-derkach-oaza approved these changes

2024-06-18 19:16 UTC, VarunNagaraju commented on docs/release-notes/5.7.44-50.md
> +    * Added a function that cleans the version string by removing invalid characters and generating a warning message.
These two points are not necessary.

2024-06-19 11:17 UTC, sleto-it requested changes

2024-06-19 11:17 UTC, sleto-it commented on docs/release-notes/5.7.44-50.md
> +Percona Server for MySQL 5.7.44-50 contains the following fixes.
The word "security" is not mentioned at all in the entire page. This looks strange to me as we are delivering security fixes with this version (part of the EOL program).  I would replace this sentence with:

"Percona Server for MySQL 5.7.44-50 includes all the features and bug fixes available in MySQL 5.7.44 Community Edition in addition to enterprise-grade features and security fixes developed by Percona."

2024-06-19 12:37 UTC, VarunNagaraju commented
@patrickbirch We need a third party library advisory section like the last time 

Openssl
======
CVE-2023-6129 
https://www.openssl.org/news/vulnerabilities.html#CVE-2023-6129
OpenSSL versions 1.1.1 and 1.0.2 are not affected by this issue.
If OpenSSL 3.x.y is being used, upgrade to one of the 3.0.13, 3.1.5, 3.2.1 versions.

- Ubuntu https://ubuntu.com/security/notices/USN-6622-1
- Debian https://security-tracker.debian.org/tracker/CVE-2023-6129
- Oracle linux https://linux.oracle.com/errata/ELSA-2024-2447.html
- Red hat https://access.redhat.com/errata/RHSA-2024:2447

Curl
===
CVE-2024-0853
https://curl.se/docs/CVE-2024-0853.html
8.5.0 is the only version affected. Rest of the versions(both higher and lower) are fine.

2024-06-19 14:19 UTC, merged