PS-9305 8.4.0-1 release notes and release note tasks
percona/psmysql-docs pull request #356
Opened 2024-07-24 16:22 UTC by patrickbirch

On branch ps-9305
	new file:   docs/release-notes/8.4.0-1.md
	modified:   docs/release-notes/release-notes-index.md
	modified:   mkdocs-base.yml
	modified:   variables.yml

2024-08-20 13:48 UTC, percona-ysorokin requested changes

2024-08-20 13:48 UTC, percona-ysorokin commented on docs/release-notes/8.4.0-1.md
> +* [PS-9219](https://perconadev.atlassian.net/browse/PS-9219): While converting the charset collation in a table, MySQL converted the date and time data types columns in the `.ibd` file. However, the
Duplicate item

2024-08-20 13:48 UTC, percona-ysorokin commented on docs/release-notes/8.4.0-1.md
> +* Install [Percona Server for MySQL 8.3]
Is this `8.3` intentional?

2024-08-20 13:48 UTC, percona-ysorokin commented on docs/release-notes/8.4.0-1.md
> +Improvements and bug fixes introduced by Oracle for MySQL 8.3 and included in Percona Server for MySQL are the following:
Is `8.3` intentional here?

2024-08-21 14:58 UTC, alina-derkach-oaza approved these changes

2024-08-22 12:30 UTC, percona-ysorokin commented on docs/release-notes/8.4.0-1.md
> +[MySQL 8.4 Release Notes]: https://dev.mysql.com/doc/relnotes/mysql/8.3/en/news-8-4-0.html
Wrong URL

2024-08-22 16:20 UTC, percona-ysorokin approved these changes
LGTM

2024-08-28 13:39 UTC, merged