PS-9181 [DOCS] - document background dictionary cache reload function…
percona/psmysql-docs pull request #440
Opened 2024-12-27 12:31 UTC by patrickbirch

…ality in the Masking Functions component 8.0

	modified:   docs/data-masking-function-list.md
	modified:   docs/data-masking-overview.md

2024-12-30 14:59 UTC, alina-derkach-oaza commented on docs/data-masking-overview.md
> +we introduced a new system variable called `component_masking_functions.dictionaries_flush_interval_seconds (read-only, integer, unsigned, default 0)`.
we -> We

2025-01-28 01:08 UTC, percona-ysorokin requested changes

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +If you change the value of the `component_masking_functions.masking_database()` system variable to something other than `mysql`, make sure to update the `GRANT` query to match the new value.
```suggestion
If you change the value of the `masking_functions.masking_database` system variable to something other than `mysql`, make sure to update the `GRANT` query to match the new value.
```

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +| [`dictionaries_flush_interval_seconds (integer, unsigned)`](#dictionaries_flush_interval_secondsinteger-unsigned) | The number of seconds between updates to the internal dictionary cache to match c
`dictionaries_flush_interval_seconds` is not a function. It is a system variable (GLOBAL,read-only, LONG INTEGER, DEFAULT 0). It should be put into a separate section `compoennt variables`.
`0` means background updates are disabled.

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +| [`masking_dictionaries(str)`](#masking_dictionariesstr) | Set a different database name to use for the dictionaries table. |
The correct name is `masking_database`. Likewise, it is not a function, it is a system variable (GLOBAL, read-only, STRING, DEFAULT "mysql"). Regardless of the value of this variable, the name of the dictionaries table will still be `masking_dictionaries` but in another database. The fill name will be `<masking_database>.masking_dictionaries`

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +## dictionaries_flush_interval_seconds(integer, unsigned)
The description is OK, but as mentioned previously, this is not a function but a component system variable `masking_functions.dictionaries_flush_interval_seconds`
(similar to `encryption_udf.dh_bits_threshold` from Encryption UDFs https://docs.percona.com/percona-server/8.0/encryption-functions.html#encryption_udfdh_bits_threshold)

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +mysql> GRANT SELECT, INSERT, UPDATE, DELETE ON <component_masking_functions.masking_database>.masking_dictionaries TO 'mysql.session'@'localhost';
```suggestion
mysql> GRANT SELECT, INSERT, UPDATE, DELETE ON <masking_functions.masking_database>.masking_dictionaries TO 'mysql.session'@'localhost';
```

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +Percona Server for MySQL 8.0.41 introduces an internal term cache. The server now uses in-memory data structures for lookups instead of querying the `mysql.masking_dictionaries` table every time. Thi
```suggestion
Percona Server for MySQL 8.0.41 introduces an internal term cache. The server now uses in-memory data structures for lookups instead of querying the `<masking_functions.masking_database>.masking_dictionaries` table every time. This improvement boosts performance, especially when handling multiple rows.
```

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +Percona Server for MySQL 8.0.41 introduces an internal term cache. The server now uses in-memory data structures for lookups instead of querying the `mysql.masking_dictionaries` table every time. Thi
```suggestion
Percona Server for MySQL 8.0.41 introduces an internal term cache. The server now uses in-memory data structures for lookups instead of querying the `<masking_functions.masking_database>.masking_dictionaries` table every time. This improvement boosts performance, especially when handling multiple rows.
```

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +## masking_database(string)
Likewise, this is not a function but a variable

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +Returns a string value of `1` (one) when successful.
```suggestion
Returns an integer value of `1` (one) when successful. 
```

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-overview.md
> +The new cache stores dictionary data in memory, making lookups faster than the previous method of querying the `mysql.masking_dictionaries` table each time. This speed boost is especially noticeable
```suggestion
The new cache stores dictionary data in memory, making lookups faster than the previous method of querying the `<masking_functions.masking_database>.masking_dictionaries` table each time. This speed boost is especially noticeable when you're working with many rows of data.
```

2025-01-28 01:08 UTC, percona-ysorokin commented on docs/data-masking-overview.md
> +To handle this, there's a new system setting called  [`component_masking_functions.dictionaries_flush_interval_seconds()`](data-masking-function-list.html#dictionaries_flush_interval_secondsinteger-u
```suggestion
To handle this, there's a new component system variable called  [`masking_functions.dictionaries_flush_interval_seconds()`](data-masking-function-list.html#dictionaries_flush_interval_secondsinteger-unsigned)
```

2025-01-28 01:13 UTC, percona-ysorokin commented on docs/data-masking-overview.md
> +To handle this, there's a new system setting called  [`component_masking_functions.dictionaries_flush_interval_seconds()`](data-masking-function-list.html#dictionaries_flush_interval_secondsinteger-u
@patrickbirch One more change we did in 8.0.41.
All dictionary manipulations functions:
* `masking_dictionary_remove()`
* `masking_dictionary_term_remove()`
* `masking_dictionary_term_add()`
now return INTEGER instead of STRING.
Old behavior: string literal "1" - success, NULL - failure
New behavior: integer 1 - success, integer 0 - failure
Please, update the description of these functions as well (probably, no versioning comments needed, just make sure that we document the `new behavior`).

2025-02-06 12:56 UTC, percona-ysorokin commented on docs/data-masking-overview.md
> +To handle this, there's a new system setting called  [`component_masking_functions.dictionaries_flush_interval_seconds()`](data-masking-function-list.html#dictionaries_flush_interval_secondsinteger-u
@patrickbirch in one of the recent post-fixes we also had to limit the max value of the `dictionaries_flush_interval_seconds` variable to 31 536 000 (60 * 60 * 24 * 365 seconds = 1 year). This needs to be reflected in the documentation as well.

2025-02-25 14:32 UTC, percona-ysorokin approved these changes
LGTM with leftovers removed

2025-02-25 14:32 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +| default      | 10000            |
The default value is `0` meaning `disabled`
```suggestion
| default      | 0                |
```

2025-02-25 14:32 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +Percona Server for MySQL 8.0.41 adds this variable. The number of seconds between a synchronization between the dictionaries table and the internal dictionary cache. The default value is 10,000 secon
```suggestion
Percona Server for MySQL 8.0.41 adds this variable. The number of seconds between a synchronization between the dictionaries table and the internal dictionary cache. The default value is 0 seconds (disabled). The minimum value is 1 second. The maximum value is 31,536,000 seconds (1 year).
```

2025-02-25 14:32 UTC, percona-ysorokin commented on docs/data-masking-function-list.md
> +Returns a string value of `1` (one) when successful.
Leftovers from `being a function` assumption. Just remove
```suggestion
```

2025-02-26 14:55 UTC, alina-derkach-oaza approved these changes

2025-02-26 14:55 UTC, merged